const MODULE_PREFIX = `PROOFREADING`

export const SET_USER_DATA = `${MODULE_PREFIX}/SET_USER_DATA`;
export const SET_ORGANIZATION_DATA = `${MODULE_PREFIX}/SET_ORGANIZATION_DATA`;

export const FETCH_VIDEO_LOADING = `${MODULE_PREFIX}/FETCH_VIDEO_LOADING`;
export const FETCH_VIDEO_FAILED = `${MODULE_PREFIX}/FETCH_VIDEO_FAILED`;
export const FETCH_VIDEO_SUCCESS = `${MODULE_PREFIX}/FETCH_VIDEO_SUCCESS`;

export const SET_STAGES = `${MODULE_PREFIX}/SET_STAGES`;

export const FETCH_ORGANIZATION_VIDEOS_LOADING = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_LOADING`;
export const FETCH_ORGANIZATION_VIDEOS_SUCCESS = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_SUCCESS`;
export const FETCH_ORGANIZATION_VIDEOS_FAILED = `${MODULE_PREFIX}/FETCH_ORGANIZATION_VIDEOS_FAILED`;

export const SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX = `${MODULE_PREFIX}/SET_ORGANIZATION_VIDEOS_ACTIVE_TAB_INDEX`;
export const SET_ORGANIZATION_VIDEOS_TABS = `${MODULE_PREFIX}/SET_ORGANIZATION_VIDEOS_TABS`;
export const SET_TRANSCRIPTION_VERSIONS = `${MODULE_PREFIX}/SET_TRANSCRIPTION_VERSIONS`
export const RESET = `${MODULE_PREFIX}/RESET`;
export const RESET_UPLOAD_VIDEO_FORM = `${MODULE_PREFIX}/RESET_UPLOAD_VIDEO_FORM`;

export const SET_UPLOAD_VIDEO_FORM = `${MODULE_PREFIX}/SET_UPLOAD_VIDEO_FORM`;
export const SET_MULTI_UPLOAD_MODE = `${MODULE_PREFIX}/SET_MULTI_UPLOAD_MODE`;


export const FETCH_ARTICLE_LOADING = `${MODULE_PREFIX}/FETCH_ARTICLE_LOADING`;
export const FETCH_ARTICLE_FAILED = `${MODULE_PREFIX}/FETCH_ARTICLE_FAILED`;
export const FETCH_ARTICLE_SUCCESS = `${MODULE_PREFIX}/FETCH_ARTICLE_SUCCESS`;

export const UPDATE_SUBSLIDE_LOADING = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_LOADING`;
export const UPDATE_SUBSLIDE_FAILED = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_FAILED`;
export const UPDATE_SUBSLIDE_SUCCESS = `${MODULE_PREFIX}/UPDATE_SUBSLIDE_SUCCESS`;

export const SET_SUBTITLES = `${MODULE_PREFIX}/SET_SUBTITLES`;
export const SET_ARTICLE = `${MODULE_PREFIX}/SET_ARTCILE`;
export const SET_SELECTED_SUBTITLE = `${MODULE_PREFIX}/SET_SELECTED_SUBTITLE`;

export const SET_TO_ENGLISH = `${MODULE_PREFIX}/SET_TO_ENGLISH`;
export const SET_NAME_SLIDES = `${MODULE_PREFIX}/SET_NAME_SLIDES`;
export const SET_UPDATE_LOADING = `${MODULE_PREFIX}/SET_UPDATE_LOADING`;
