export const HEARTBEAT = 'COMET_HEARTBEAT';
export const HUMANVOICE_AUDIO_PROCESSING = 'HUMANVOICE_AUDIO_PROCESSING';
export const AUTHENTICATE = 'AUTHENTICATE';
export const NEW_NOTIFICATION = 'NEW_NOTIFICATION';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAILED = 'AUTHENTICATE_FAILED';
export const RECORDED_AUDIO_PROCESSED = 'RECORDED_AUDIO_PROCESSED';
export const TRANSLATION_SUBSLIDE_CHANGE = 'TRANSLATION_SUBSLIDE_CHANGE';

export const VIDEO_UPLOADED = 'VIDEO_UPLOADED';
export const VIDEO_TRANSCRIBED = 'VIDEO_TRANSCRIBED';
export const VIDEO_DONE = 'VIDEO_DONE';
export const DOWNLOAD_FILE = 'DOWNLOAD_FILE';
export const EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH = 'EXTRACT_VIDEO_BACKGROUND_MUSIC_FINISH'
export const NOISE_CANCELLATION_VIDEO_FINISH = `NOISE_CANCELLATION_VIDEO_FINISH`;
export const AI_TRANSCRIBE_VIDEO_FINISH = `AI_TRANSCRIBE_VIDEO_FINISH`;
export const AUTOMATIC_VIDEO_BREAKING_DONE = `AUTOMATIC_VIDEO_BREAKING_DONE`;